- name: Creates directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mysql_check_user }}"
    group: "{{ mysql_check_group }}"
  with_items:
    - "{{ mysql_check_home }}/bin"
    - "{{ mysql_check_home }}/conf"

- name: Download mysql-check
  become: yes
  get_url:
    url: "{{ mysql_check_url }}"
    checksum: "md5:0b5a84cf51fcf79480b4f36b4c88153b."
    dest: "{{ mysql_check_home }}/bin"
    owner: "{{ mysql_check_user }}"
    group: "{{ mysql_check_group }}"
    mode: 755
    
- name: Copy conf files
  become: yes
  template:
    src: mysql-check.conf.j2
    dest: "{{ mysql_check_home }}/conf/mysql-check.conf"
    owner: "{{ mysql_check_user }}"
    group: "{{ mysql_check_group }}"
  notify: mysql-check restart
  
- name: Copy mysql-check Service File
  become: yes
  template:
    src: mysql-check.service.j2
    dest: /usr/lib/systemd/system/mysql-check.service

- name: Ensure mysql-check Service Enabled and Running
  become: yes
  systemd:
    name: mysql-check
    state: started
    enabled: yes