plugin: google.cloud.gcp_compute
projects:
  - devops-lab-summer
filters: 
  - 'name = prod*' 
auth_kind: serviceaccount
service_account_file: /home/obstaclex/servicekey/terraform.json
groups:
  web: "'webapp' in name"
  db: "'db' in name"