- name: Installing webapp-server
  hosts: webapp-server
  vars:
    webapp_user: webapp-server
    webapp_group: webapp-server
    webapp_url: https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/webapp-server/webapp-server
    FirstName: Ilya
    LastName: Melnik

  tasks:
  - name: Create webapp-server Group
    become: yes
    group:
      name: "{{ webapp_group }}"
  
  - name: Add user "webapp-server"
    become: yes
    user: 
      name: "{{ webapp_user }}"
      group: "{{ webapp_group }}"
      home: /opt/webapp-server
  
  - name: Creates directory
    become: yes
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ webapp_user }}"
      group: "{{ webapp_group }}"
    with_items:
    - /opt/webapp-server/bin
    - /opt/webapp-server/conf
  
  - name: Download webapp
    become: yes
    get_url:
      url: "{{ webapp_url }}"
      checksum: "md5:5c3c40891637abc42460e92c82ea4b30."
      dest: /opt/webapp-server/bin
      owner: "{{ webapp_user }}"
      group: "{{ webapp_group }}"
      mode: 755
  
  - name: Copy conf files
    become: yes
    template:
      src: files/webapp-server.conf.j2
      dest: /opt/webapp-server/conf/webapp-server.conf
      owner: "{{ webapp_user }}"
      group: "{{ webapp_group }}"
    notify: webapp restart
  
  - name: Copy webapp-server Service File
    become: yes
    copy:
      src: files/webapp-server.service
      dest: /usr/lib/systemd/system/webapp-server.service
  
  - name: Ensure webapp-server Service Enabled and Running
    become: yes
    systemd:
      name: webapp-server
      state: started
      enabled: yes
  
  handlers:
  - name: webapp restart
    become: yes
    systemd:
      name: webapp-server
      state: restarted