- name: Add group
  become: yes
  group:
    name: "{{ group }}"
  
- name: Add user 
  become: yes
  user: 
    name: "{{ user }}"
    group: "{{ group }}"
    home: "{{ homedir }}"

- name: Add sudoers
  become: yes
  template:
    src: user.sudoers.j2
    dest: /etc/sudoers.d/{{ user }}